### ISSUE TITLE
Various possible improvements

### ISSUE THREAD

**Issue by localhostdotdev** [BjoernKW/PivotHelper#3]
I see you are reading the issues so might as well add the issues I got from my usage (just looking at a ~150 rows, ~12 columns (mostly numbers) CSV file.

- I have to zoom out to see all the labels in "bar chart" mode
- When selecting a label under the chart I don't the corresponding value
- ~~Would be nice to filter out on minimum / maximum, e.g. only show value where the y value is more than 1000~~ see https://github.com/BjoernKW/PivotHelper/issues/4
- ~~Also having the top X values displayed (e.g. top 10 / 100 / 1000)~~ see https://github.com/BjoernKW/PivotHelper/issues/4
- ~~Also filtering out on non-displayed column would be nice~~ see https://github.com/BjoernKW/PivotHelper/issues/4
- ~~Working with booleans would be nice too~~ see https://github.com/BjoernKW/PivotHelper/issues/8
- ~~Examples on how to use it~~

**Comment by BjoernKW** [comment]
As for these two issues please file a ticket with PivotTable.js:

- I have to zoom out to see all the labels in "bar chart" mode
- When selecting a label under the chart I don't the corresponding value

https://github.com/nicolaskruchten/pivottable/issues
